[package]
name = "dms-toolkit-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
calamine = "0.32.0"
chardetng = "0.1.17"
dashmap = "6.1.0"
docx-rs = "0.4.18"
encoding_rs = "0.8.35"
napi = "3.6.1"
napi-derive = "3.4.0"
pdf-extract = "0.10.0"
rayon = "1.11.0"
